pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(Maven: 'apache-maven-3.6.3',mavenSettingsConfig: 'my-maven-settings') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(Maven: 'apache-maven-3.6.3',mavenSettingsConfig: 'my-maven-settings') {
                    sh 'mvn test'
                }
            }
        }


        stage ('Deployment Stage') {
            steps {
                withMaven(Maven: 'apache-maven-3.6.3',mavenSettingsConfig: 'my-maven-settings') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}
